{{- if .Values.enabled -}}{{/* ENABLED */}}
{{- if eq (include "gitlab.ingress.enabled" $) "true" -}}{{/* INGRESS ENABLED */}}
{{- $gitlabHostname := include "gitlab.gitlab.hostname" $ -}}
{{- if .Values.global.hosts.gitlab.hostnameOverride -}}
{{-   $gitlabHostname = .Values.global.hosts.gitlab.hostnameOverride -}}
{{- end -}}
{{- $tlsSecret := include "webservice.tlsSecret" $ -}}
{{- include "webservice.datamodel.prepare" $ -}}
{{/* BEGIN range deployments */}}
{{- range $.Values.deployments -}}
{{-   if .ingress.path -}}{{/* SET .ingress.path */}}
{{/*
From here on:
- `.` is `.deployments.xyz` value
- `.name` is the key (xyz)
*/}}
{{- $ingressCfg := dict "global" $.Values.global.ingress "local" .ingress "context" $ -}}
---
apiVersion: {{ template "gitlab.ingress.apiVersion" $ingressCfg }}
kind: Ingress
metadata:
  name: {{ template "webservice.fullname.withSuffix" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" $ | nindent 4 }}
    {{- include "webservice.labels" . | nindent 4 }}
    {{- include "webservice.commonLabels" . | nindent 4 }}
  annotations:
    {{ include "ingress.class.annotation" $ingressCfg }}
    kubernetes.io/ingress.provider: "{{ template "gitlab.ingress.provider" $ingressCfg }}"
    {{- if eq "nginx" (default $.Values.global.ingress.provider .ingress.provider) }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .ingress.proxyBodySize | quote }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ .ingress.proxyReadTimeout | quote }}
    nginx.ingress.kubernetes.io/proxy-connect-timeout: {{ .ingress.proxyConnectTimeout | quote }}
    {{- end }}
    {{ include "gitlab.certmanager_annotations" $ }}
  {{- range $key, $value := merge .ingress.annotations $.Values.global.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  {{ include "ingress.class.field" $ingressCfg }}
  rules:
    - host: {{ $gitlabHostname }}
      http:
        paths:
          - path: {{ .ingress.path }}
            {{ if or ($.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress") (eq $.Values.global.ingress.apiVersion "networking.k8s.io/v1") -}}
            pathType: {{ default .ingress.pathType $.Values.global.ingress.pathType }}
            backend:
              service:
                  name: {{ template "webservice.fullname.withSuffix" . }}
                  port:
                    number: {{ $.Values.service.workhorseExternalPort }}
            {{- else -}}
            backend:
              serviceName: {{ template "webservice.fullname.withSuffix" . }}
              servicePort: {{ $.Values.service.workhorseExternalPort }}
            {{- end -}}
  {{- if (and $tlsSecret (eq (include "gitlab.ingress.tls.enabled" $) "true" )) }}
  tls:
    - hosts:
      - {{ $gitlabHostname }}
      secretName: {{ $tlsSecret }}
  {{- else }}
  tls: []
  {{- end }}
{{- end -}}
{{- end -}}{{/* SET .ingress.path */}}
{{- end -}}{{/* INGRESS ENABLED */}}
{{- end -}}{{/* ENABLED */}}
