{{- $externalAddresses := concat $.Values.global.pages.externalHttp $.Values.global.pages.externalHttps | uniq }}
{{- if empty ($externalAddresses) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
    {{- include "gitlab.commonLabels" . | nindent 4 }}
    {{- include "gitlab.serviceLabels" . | nindent 4 }}
  annotations:
    {{- include "gitlab.serviceAnnotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort | int }}
      targetPort: {{ .Values.service.internalPort | int }}
      protocol: TCP
      name: http-{{ template "name" . }}-proxy
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
{{- end }}
