apiVersion: v2
appVersion: 0.2.15
description: Zookeeper Operator Helm chart for Kubernetes
home: https://github.com/pravega/zookeeper-operator
icon: https://zookeeper.apache.org/images/zookeeper_small.gif
keywords:
- zookeeper
- storage
name: zookeeper-operator
version: 0.2.15
