apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    {{- include "labels" . | nindent 4 }}
  name: {{ .Chart.Name }}
webhooks:
- admissionReviewVersions: ["v1"]
  clientConfig:
    service:
      name: {{ .Chart.Name }}
      namespace: {{ .Release.Namespace }}
  name: reef.inaccel.com
  objectSelector:
    matchLabels:
      inaccel/fpga: enabled
  sideEffects: None
