apiVersion: v1
appVersion: 13.23.2
description: sshd for Gitlab
home: https://about.gitlab.com/
icon: https://gitlab.com/gitlab-com/gitlab-artwork/raw/master/logo/logo-square.svg
keywords:
- gitlab
- sshd
- ssh
maintainers:
- email: support@gitlab.com
  name: GitLab Inc.
name: gitlab-shell
sources:
- https://gitlab.com/gitlab-org/charts/gitlab/tree/master/charts/gitlab/charts/gitlab-shell
- https://gitlab.com/gitlab-org/build/CNG/tree/master/gitlab-shell
version: 5.8.2
